/** 
 * @TITLE V_AQ_WO_CRW1_BOM
 * @ABOUT 
 * @AUTHOR JEREMY HEMINGER
 * @DATE OCTOBER 30, 2025
 * @LAST_UPDATE november 4, 2025
 * 
 * @DEPENDENCIES
 * - V_WO_CRW1
 * - V_AQ_BOM_RECURS_6
 * - V_AQ_BOM_LOOKUP
 * 
 * @VERSION 1.0.0.0
 * @LIVE TRUE
 * */

-- PIVOT VERSION
CREATE OR REPLACE VIEW V_AQ_WO_CRW1_BOM_PIVOT AS
SELECT DISTINCT
    VW.WORKORDER_ID,
    VW.BUCKET,
    VW.CYCLES_REQ,
    VW.PRODHRS,
    VW.START_TIME,
    VW.END_TIME,
    VW.ARCUSTO_ID,
    VW.PARTNO_ID,
    VW.PTORDER_ID,
    VV.SNDOP_ID,
    VV.OPMAT_ID,
    VV.STANDARD_ID,
    VV.MFGNO,
    VV.ITEMNO,
    (SELECT PHANTOM FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS PHANTOM,
    (SELECT CLASS FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS CLASS,
    (SELECT DESCRIP FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS DESCRIP,
    (SELECT REV FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS REV,
    (SELECT SCRAP FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS SCRAP,
    (SELECT PTSPER FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS PTSPER,
    (SELECT UNIT FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS UNIT,
    (SELECT PTSPER_DISP FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS PTSPER_DISP,
    (SELECT ACTCAV FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS ACTCAV,
    (SELECT ROUTING_NOTE FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS ROUTING_NOTE,
    (SELECT PTWT_DISP FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS PTWT_DISP,
    (SELECT MFG_TYPE FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS MFG_TYPE,
    (SELECT UOM FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS UOM,
    (SELECT SETS_DISP FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS SETS_DISP,
    (SELECT LBSK FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS LBSK,
    (SELECT ARINVT_ID_MAT FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS ARINVT_ID_MAT,
    (SELECT M.STANDARD_MFGTYPE FROM MFGTYPE M, STANDARD S WHERE S.ID = VV.STANDARD_ID AND M.MFGTYPE = S.MFG_TYPE AND ROWNUM = 1) AS STANDARD_MFGTYPE,
    (SELECT ARINVT_ID FROM SNDOP WHERE ID = VV.SNDOP_ID AND ROWNUM = 1) AS SNDOP_ARINVT_ID,
    (SELECT OPNO FROM SNDOP WHERE ID = VV.SNDOP_ID AND ROWNUM = 1) AS OPNO,
    (SELECT REL_QUAN FROM PTORDER_REL WHERE PTORDER_ID = VW.PTORDER_ID AND ROWNUM = 1) AS REL_QUAN,
    1 AS CHILD_LEVEL,
    VV.CHILD_LEVEL_ONE_ARINVT_ID AS CHILD_LEVEL_ARINVT_ID,
    VV.CHILD_LEVEL_ONE_ITEMNO AS CHILD_ITEMNO,
    VV.CHILD_LEVEL_ONE_OPMAT_ID AS CL_OPMAT_ID,
    (SELECT DESCRIP FROM ARINVT WHERE ID = VV.CHILD_LEVEL_ONE_ARINVT_ID) AS CHILD_DESCRIP,
    (SELECT CLASS FROM ARINVT WHERE ID = VV.CHILD_LEVEL_ONE_ARINVT_ID) AS CHILD_CLASS,
    (SELECT REV FROM ARINVT WHERE ID = VV.CHILD_LEVEL_ONE_ARINVT_ID) AS CHILD_REV,
    (SELECT SCRAP FROM OPMAT WHERE ID = VV.CHILD_LEVEL_ONE_OPMAT_ID) AS CHILD_SCRAP,
    (SELECT PTSPER FROM OPMAT WHERE ID = VV.CHILD_LEVEL_ONE_OPMAT_ID) AS CHILD_PTSPER,
    (SELECT UNIT FROM OPMAT WHERE ID = VV.CHILD_LEVEL_ONE_OPMAT_ID) AS CHILD_UNIT,
    (SELECT PTSPER_DISP FROM OPMAT WHERE ID = VV.CHILD_LEVEL_ONE_OPMAT_ID) AS CHILD_PTSPER_DISP,
    (VW.CYCLES_REQ * (SELECT PTSPER FROM OPMAT WHERE ID = VV.CHILD_LEVEL_ONE_OPMAT_ID)) AS TOTAL_REQ
FROM 
    V_WO_CRW1 VW
    JOIN V_AQ_BOM_RECURS_6 VV ON VW.STANDARD_ID = VV.STANDARD_ID

UNION ALL

SELECT DISTINCT
    VW.WORKORDER_ID,
    VW.BUCKET,
    VW.CYCLES_REQ,
    VW.PRODHRS,
    VW.START_TIME,
    VW.END_TIME,
    VW.ARCUSTO_ID,
    VW.PARTNO_ID,
    VW.PTORDER_ID,
    VV.SNDOP_ID,
    VV.OPMAT_ID,
    VV.STANDARD_ID,
    VV.MFGNO,
    VV.ITEMNO,
    (SELECT PHANTOM FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS PHANTOM,
    (SELECT CLASS FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS CLASS,
    (SELECT DESCRIP FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS DESCRIP,
    (SELECT REV FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS REV,
    (SELECT SCRAP FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS SCRAP,
    (SELECT PTSPER FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS PTSPER,
    (SELECT UNIT FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS UNIT,
    (SELECT PTSPER_DISP FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS PTSPER_DISP,
    (SELECT ACTCAV FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS ACTCAV,
    (SELECT ROUTING_NOTE FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS ROUTING_NOTE,
    (SELECT PTWT_DISP FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS PTWT_DISP,
    (SELECT MFG_TYPE FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS MFG_TYPE,
    (SELECT UOM FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS UOM,
    (SELECT SETS_DISP FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS SETS_DISP,
    (SELECT LBSK FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS LBSK,
    (SELECT ARINVT_ID_MAT FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS ARINVT_ID_MAT,
    (SELECT M.STANDARD_MFGTYPE FROM MFGTYPE M, STANDARD S WHERE S.ID = VV.STANDARD_ID AND M.MFGTYPE = S.MFG_TYPE AND ROWNUM = 1) AS STANDARD_MFGTYPE,
    (SELECT ARINVT_ID FROM SNDOP WHERE ID = VV.SNDOP_ID AND ROWNUM = 1) AS SNDOP_ARINVT_ID,
    (SELECT OPNO FROM SNDOP WHERE ID = VV.SNDOP_ID AND ROWNUM = 1) AS OPNO,
    (SELECT REL_QUAN FROM PTORDER_REL WHERE PTORDER_ID = VW.PTORDER_ID AND ROWNUM = 1) AS REL_QUAN,
    2 AS CHILD_LEVEL,
    VV.CHILD_LEVEL_TWO_ARINVT_ID AS CHILD_LEVEL_ARINVT_ID,
    VV.CHILD_LEVEL_TWO_ITEMNO AS CHILD_ITEMNO,
    VV.CHILD_LEVEL_TWO_OPMAT_ID AS CL_OPMAT_ID,
    (SELECT DESCRIP FROM ARINVT WHERE ID = VV.CHILD_LEVEL_TWO_ARINVT_ID) AS CHILD_DESCRIP,
    (SELECT CLASS FROM ARINVT WHERE ID = VV.CHILD_LEVEL_TWO_ARINVT_ID) AS CHILD_CLASS,
    (SELECT REV FROM ARINVT WHERE ID = VV.CHILD_LEVEL_TWO_ARINVT_ID) AS CHILD_REV,
    (SELECT SCRAP FROM OPMAT WHERE ID = VV.CHILD_LEVEL_TWO_OPMAT_ID) AS CHILD_SCRAP,
    (SELECT PTSPER FROM OPMAT WHERE ID = VV.CHILD_LEVEL_TWO_OPMAT_ID) AS CHILD_PTSPER,
    (SELECT UNIT FROM OPMAT WHERE ID = VV.CHILD_LEVEL_TWO_OPMAT_ID) AS CHILD_UNIT,
    (SELECT PTSPER_DISP FROM OPMAT WHERE ID = VV.CHILD_LEVEL_TWO_OPMAT_ID) AS CHILD_PTSPER_DISP,
    (VW.CYCLES_REQ * (SELECT PTSPER FROM OPMAT WHERE ID = VV.CHILD_LEVEL_TWO_OPMAT_ID)) AS TOTAL_REQ
FROM 
    V_WO_CRW1 VW
    JOIN V_AQ_BOM_RECURS_6 VV ON VW.STANDARD_ID = VV.STANDARD_ID

UNION ALL

SELECT DISTINCT
    VW.WORKORDER_ID,
    VW.BUCKET,
    VW.CYCLES_REQ,
    VW.PRODHRS,
    VW.START_TIME,
    VW.END_TIME,
    VW.ARCUSTO_ID,
    VW.PARTNO_ID,
    VW.PTORDER_ID,
    VV.SNDOP_ID,
    VV.OPMAT_ID,
    VV.STANDARD_ID,
    VV.MFGNO,
    VV.ITEMNO,
    (SELECT PHANTOM FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS PHANTOM,
    (SELECT CLASS FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS CLASS,
    (SELECT DESCRIP FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS DESCRIP,
    (SELECT REV FROM ARINVT WHERE ID = VV.ARINVT_ID AND ROWNUM = 1) AS REV,
    (SELECT SCRAP FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS SCRAP,
    (SELECT PTSPER FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS PTSPER,
    (SELECT UNIT FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS UNIT,
    (SELECT PTSPER_DISP FROM OPMAT WHERE ID = VV.OPMAT_ID AND ROWNUM = 1) AS PTSPER_DISP,
    (SELECT ACTCAV FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS ACTCAV,
    (SELECT ROUTING_NOTE FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS ROUTING_NOTE,
    (SELECT PTWT_DISP FROM PARTNO WHERE ID = VV.PARTNO_ID AND ROWNUM = 1) AS PTWT_DISP,
    (SELECT MFG_TYPE FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS MFG_TYPE,
    (SELECT UOM FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS UOM,
    (SELECT SETS_DISP FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS SETS_DISP,
    (SELECT LBSK FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS LBSK,
    (SELECT ARINVT_ID_MAT FROM STANDARD WHERE ID = VV.STANDARD_ID AND ROWNUM = 1) AS ARINVT_ID_MAT,
    (SELECT M.STANDARD_MFGTYPE FROM MFGTYPE M, STANDARD S WHERE S.ID = VV.STANDARD_ID AND M.MFGTYPE = S.MFG_TYPE AND ROWNUM = 1) AS STANDARD_MFGTYPE,
    (SELECT ARINVT_ID FROM SNDOP WHERE ID = VV.SNDOP_ID AND ROWNUM = 1) AS SNDOP_ARINVT_ID,
    (SELECT OPNO FROM SNDOP WHERE ID = VV.SNDOP_ID AND ROWNUM = 1) AS OPNO,
    (SELECT REL_QUAN FROM PTORDER_REL WHERE PTORDER_ID = VW.PTORDER_ID AND ROWNUM = 1) AS REL_QUAN,
    3 AS CHILD_LEVEL,
    VV.CHILD_LEVEL_THREE_ARINVT_ID AS CHILD_LEVEL_ARINVT_ID,
    VV.CHILD_LEVEL_THREE_ITEMNO AS CHILD_ITEMNO,
    VV.CHILD_LEVEL_THREE_OPMAT_ID AS CL_OPMAT_ID,
    (SELECT DESCRIP FROM ARINVT WHERE ID = VV.CHILD_LEVEL_THREE_ARINVT_ID) AS CHILD_DESCRIP,
    (SELECT CLASS FROM ARINVT WHERE ID = VV.CHILD_LEVEL_THREE_ARINVT_ID) AS CHILD_CLASS,
    (SELECT REV FROM ARINVT WHERE ID = VV.CHILD_LEVEL_THREE_ARINVT_ID) AS CHILD_REV,
    (SELECT SCRAP FROM OPMAT WHERE ID = VV.CHILD_LEVEL_THREE_OPMAT_ID) AS CHILD_SCRAP,
    (SELECT PTSPER FROM OPMAT WHERE ID = VV.CHILD_LEVEL_THREE_OPMAT_ID) AS CHILD_PTSPER,
    (SELECT UNIT FROM OPMAT WHERE ID = VV.CHILD_LEVEL_THREE_OPMAT_ID) AS CHILD_UNIT,
    (SELECT PTSPER_DISP FROM OPMAT WHERE ID = VV.CHILD_LEVEL_THREE_OPMAT_ID) AS CHILD_PTSPER_DISP,
    (VW.CYCLES_REQ * (SELECT PTSPER FROM OPMAT WHERE ID = VV.CHILD_LEVEL_THREE_OPMAT_ID)) AS TOTAL_REQ
FROM 
    V_WO_CRW1 VW
    JOIN V_AQ_BOM_RECURS_6 VV ON VW.STANDARD_ID = VV.STANDARD_ID
ORDER BY WORKORDER_ID, CHILD_LEVEL;
